[package]
name = "efi-key-enroller"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.27"
uefi = { version = "0.35.0", features = ["logger", "panic_handler", "alloc"] }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = true
