name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          rustup update
          rustup target add x86_64-unknown-uefi
          rustup component add rust-src
      - name: Build
        run: cargo build --release --verbose
      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            target/x86_64-unknown-uefi/release/efi-key-enroller.efi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: efi-key-enroller
          path: target/x86_64-unknown-uefi/release/efi-key-enroller.efi
