name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        rustup update
        rustup target add x86_64-unknown-uefi
        rustup component add rust-src
    - name: Build
      run: cargo build --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: efi-key-enroller
        path: target/x86_64-unknown-uefi/release/efi-key-enroller.efi
